# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0002_auto_20160809_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
