# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0003_pin_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='interest',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
