# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pins', '0004_pin_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
